Repository mediamonks/react-kit, pull requests merged in 2024-02, with the labels that each got.

#307 Memoize resize callback
  src/hooks/useContentRect/useContentRect.ts
  src/hooks/useContentRectState/useContentRectState.ts
  src/hooks/useResizeObserver/useResizeObserver.ts
Labels: bug

#277 Add PolymorphicComponentProps
  src/index.ts
  src/types/PolymorphicComponentProps/PolymorphicComponentProps.mdx
  src/types/PolymorphicComponentProps/PolymorphicComponentProps.ts
Labels: enhancement, help wanted

#309 Create separate entries for gsap and nextjs
  package.json
  src/gsap.ts
  src/index.ts
  src/nextjs.ts
Labels: bug, enhancement, breaking change
